# Generated by Django 3.1.7 on 2021-02-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rolelist',
            table='list_roles',
        ),
    ]
