# Generated by Django 3.1.7 on 2021-02-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20210221_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolelist',
            name='Id',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
