# Generated by Django 3.1.7 on 2021-02-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20210222_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolelist',
            name='Id',
            field=models.CharField(max_length=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Id',
            field=models.CharField(max_length=250),
        ),
    ]
